### ISSUE TITLE
Created use case by relation of entities.

### ISSUE THREAD

**Issue by Porping** [team-inu/inu-backyard#6]
- [ ] Created use case between entities.
- [ ] Mapping use case for reducing unnecessary use case.

link: [Doc](https://docs.google.com/document/d/1SVK9JnyBWgS5PBLBuq8BoDXcJeiPOz_SEvzqoyzgxhY/edit?usp=sharing)

**Comment by XiaoXuxxxx** [comment]
We will create individual issues for each entity.
